version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_copiloto
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: copiloto_vendas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: copiloto_backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Monta o diretório atual (código fonte) no container

volumes:
  mysql_data:
